config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles #, only: [:show]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 2, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# ArticlesController
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def show; end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, notice: 'Article was successfully destroyed.'
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User was successfully created'
      redirect_to articles_path
    else
      render 'new', status: :unprocessable_entity
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<div class="container">

  <%= form_with model: @article, class: 'shadow mb-3 bg-info rounded p-3' do |form| %>

    <%= render 'shared/errors', obj: @article %>

    <div class="row mt-4">
      <%= form.label :title, style: "display: block", class: 'col-2 col-form-label text-light' %>
      <div class="col-10">
        <%= form.text_field :title, class: 'form-control shadow rounded', placeholder: "Title" %>
      </div>
    </div>

    <div class="row mt-4">
      <%= form.label :description, style: "display: block", class: 'col-2 col-form-label text-light' %>
      <div class="col-10">
        <%= form.text_area :description, rows: 10, class: 'form-control shadow rounded', placeholder: "Description" %>
      </div>
    </div>

    <div class="mt-4 text-center">
      <%= form.submit class: 'btn btn-outline-light btn-lg' %>
    </div>
  <% end %>

  <div class="text-center mb-3">
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: 'text-info' %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit Article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<div class="text-center">
  <%= link_to 'New Article', new_article_path, class: 'btn btn-primary' %>
</div>

<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            by <%= article.user.username %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: 'text-success' %></h5>
            <p class="card-text"><%= truncate(article.description, length: 300) %></p>
            <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-info' %>
            <%= link_to 'Delete', article_path(article), class: 'btn btn-outline-danger',
                        data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
          </div>
          <div class="card-footer text-body-secondary">
            <div class="small"><%= "Created #{time_ago_in_words(article.created_at)} ago" %></div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">New Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          by <%= @article.user.username %>
        </div>
        <div class="card-body">
          <div class="card-text text-start">
            <%= simple_format(@article.description) %>
          </div>
          <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-info' %>
          <%= link_to 'Delete', article_path(@article), class: 'btn btn-outline-danger',
                      data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        </div>
        <div class="card-footer text-body-secondary">
          <div class="small"><%= "Created #{time_ago_in_words(@article.created_at)} ago" %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="text-center">
  <%= link_to '[ Return to articles listing ]', articles_path, class: 'text-info' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'shared/navbar' %>
    <div id="page-content">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
        featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to 'Sign up!', signup_path, class: 'btn btn-success btn-lg' %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading"><%= pluralize(obj.errors.count, "error") %>
      prohibited this <%= obj.class.name.downcase %> from being saved:</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="container">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Alpha Blog &copy; 2023</small>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'ALPHA BLOG', root_path, id: 'logo', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li><a><%= link_to 'Create new article',new_article_path, class: 'dropdown-item' %></a></li>
            <li><a><%= link_to 'View articles',articles_path, class: 'dropdown-item' %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="container">

  <%= form_with model: @user, class: 'shadow mb-3 bg-info rounded p-3' do |form| %>

    <%= render 'shared/errors', obj: @user %>

    <div class="row mt-4">
      <%= form.label :username, style: "display: block", class: 'col-2 col-form-label text-light' %>
      <div class="col-10">
        <%= form.text_field :username, class: 'form-control shadow rounded', placeholder: "User name" %>
      </div>
    </div>

    <div class="row mt-4">
      <%= form.label :email, style: "display: block", class: 'col-2 col-form-label text-light' %>
      <div class="col-10">
        <%= form.email_field :email, class: 'form-control shadow rounded', placeholder: "E-mail" %>
      </div>
    </div>

    <div class="row mt-4">
      <%= form.label :password, style: "display: block", class: 'col-2 col-form-label text-light' %>
      <div class="col-10">
        <%= form.password_field :password, class: 'form-control shadow rounded', placeholder: "Password" %>
      </div>
    </div>

    <div class="mt-4 text-center">
      <%= form.submit 'Sign up', class: 'btn btn-outline-light btn-lg' %>
    </div>
  <% end %>

  <div class="text-center mb-3">
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: 'text-info' %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up</h1>
<%= render 'form' %>